#设置服务启动端口
server:
  port: 10001
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.106.130:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#整合Mybatis-Plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #设置自增主键

